symfony/src/Maith/JuicioCiudadanoBundle/Entity/JuicioPrensa.php
<?php

namespace Maith\JuicioCiudadanoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * MaithArticle
 *
 * @ORM\Table(name="juicio_prensa")
 * @ORM\Entity(repositoryClass="Gedmo\Sortable\Entity\Repository\SortableRepository")
 */
class JuicioPrensa
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="preface", type="string", length=255, nullable=true)
     */
    private $preface;

    /**
     * @var string
     *
     * @ORM\Column(name="body", type="text", nullable=true)
     */
    private $body;


    /**
     * @var integer
     *
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer")
     */
    private $position = 0;

    /**
      * @var datetime $created
      *
      * @Gedmo\Timestampable(on="create")
      * @ORM\Column(type="datetime")
      */
     private $created;

    /**
     * @var datetime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;
    
    
    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(name="slug", type="string", length=255)
     */    
    private $slug;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return MaithArticle
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set preface
     *
     * @param string $preface
     * @return MaithArticle
     */
    public function setPreface($preface)
    {
        $this->preface = $preface;

        return $this;
    }

    /**
     * Get preface
     *
     * @return string 
     */
    public function getPreface()
    {
        return $this->preface;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return MaithArticle
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string 
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set position
     *
     * @param integer $position
     * @return MaithArticle
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return integer 
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return MaithArticle
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return MaithArticle
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return MaithArticle
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
    
    public function getFullClassName()
    {
      return get_class($this);
    }
    
    public function retrieveAlbums()
    {
      return array('gallery');
    }
    
    public function checkAlbumForOnlineVideo($name)
    {
      if($name == 'gallery')
      {
        return true;
      }
      return false;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        
    }

}

symfony/src/Maith/JuicioCiudadanoBundle/Form/JuicioPrensaType.php
<?php

namespace Maith\JuicioCiudadanoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class JuicioPrensaType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('preface')
            ->add('body')
            ->add('position')
            //->add('created')
            //->add('updated')
            //->add('slug')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Maith\JuicioCiudadanoBundle\Entity\JuicioPrensa'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'maith_juiciociudadanobundle_juicioprensa';
    }
}

symfony/src/Maith/JuicioCiudadanoBundle/Controller/JuicioPrensaController.php
<?php

namespace Maith\JuicioCiudadanoBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Maith\JuicioCiudadanoBundle\Entity\JuicioPrensa;
use Maith\JuicioCiudadanoBundle\Form\JuicioPrensaType;

/**
 * JuicioPrensa controller.
 *
 */
class JuicioPrensaController extends Controller
{

    /**
     * Lists all JuicioPrensa entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('MaithJuicioCiudadanoBundle:JuicioPrensa')->findAll();

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:index.html.twig', array(
            'entities' => $entities,
            'activemenu' => 'article',
        ));
    }
    /**
     * Creates a new JuicioPrensa entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new JuicioPrensa();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();
            $this->get('session')->getFlashBag()->add('notif-success', 'Articulo de prensa creado con exito');
            return $this->redirect($this->generateUrl('admin_prensa_edit', array('id' => $entity->getId())));
        }
        else
        {
            $this->get('session')->getFlashBag()->add('notif-error', 'A ocurrido un error con el formulario. Revisa los campos.');
        }

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'activemenu' => 'article',
        ));
    }

    /**
     * Creates a form to create a JuicioPrensa entity.
     *
     * @param JuicioPrensa $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(JuicioPrensa $entity)
    {
        $form = $this->createForm(new JuicioPrensaType(), $entity, array(
            'action' => $this->generateUrl('admin_prensa_create'),
            'method' => 'POST',
        ));

        //$form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new JuicioPrensa entity.
     *
     */
    public function newAction()
    {
        $entity = new JuicioPrensa();
        $form   = $this->createCreateForm($entity);

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'activemenu' => 'article',
        ));
    }

    /**
     * Finds and displays a JuicioPrensa entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MaithJuicioCiudadanoBundle:JuicioPrensa')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find JuicioPrensa entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'activemenu' => 'article',
        ));
    }

    /**
     * Displays a form to edit an existing JuicioPrensa entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MaithJuicioCiudadanoBundle:JuicioPrensa')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find JuicioPrensa entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'activemenu' => 'article',
        ));
    }

    /**
    * Creates a form to edit a JuicioPrensa entity.
    *
    * @param JuicioPrensa $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(JuicioPrensa $entity)
    {
        $form = $this->createForm(new JuicioPrensaType(), $entity, array(
            'action' => $this->generateUrl('admin_prensa_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //$form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing JuicioPrensa entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MaithJuicioCiudadanoBundle:JuicioPrensa')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find JuicioPrensa entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();
            $this->get('session')->getFlashBag()->add('notif-success', 'Articulo de prensa actualizado con exito');
            return $this->redirect($this->generateUrl('admin_prensa_edit', array('id' => $id)));
        }
        else
        {
            $this->get('session')->getFlashBag()->add('notif-error', 'A ocurrido un error con el formulario. Revisa los campos.');
        }

        return $this->render('MaithJuicioCiudadanoBundle:JuicioPrensa:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'activemenu' => 'article',
        ));
    }
    /**
     * Deletes a JuicioPrensa entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('MaithJuicioCiudadanoBundle:JuicioPrensa')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find JuicioPrensa entity.');
            }

            $em->remove($entity);
            $em->flush();
            $this->get('session')->getFlashBag()->add('notif-success', 'Articulo de prensa eliminado con exito');
        }

        return $this->redirect($this->generateUrl('admin_prensa'));
    }

    /**
     * Creates a form to delete a JuicioPrensa entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_prensa_delete', array('id' => $id)))
            ->setMethod('DELETE')
            //->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

symfony/src/Maith/JuicioCiudadanoBundle/Resources/views/JuicioPrensa/edit.html.twig
{% extends 'MaithJuicioCiudadanoBundle::adminlayout.html.twig' %}
{% block pagestylesheets %}
  <link rel="stylesheet" type="text/css" href="{{ asset('bundles/maithcommonimage/css/maithalbums.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ asset('bundles/maithcommonadmin/css/colorbox.css') }}" />
{% endblock %}
{% block javascripts %}
  <script type="text/javascript" src="{{ asset('bundles/maithcommonadmin/js/jquery.colorbox-min.js') }}"></script>    
  <script type="text/javascript" src="{{ asset('bundles/maithcommonimage/js/imagesManager.js') }}"></script>    
  <script src="{{ asset('bundles/maithjuiciociudadano/admin/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ asset('bundles/maithjuiciociudadano/admin/js/basicstarttinymce.js') }}"></script>
{% endblock %}

{% block body -%}
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">Actualizar prensa</header>
      <div class="panel-body">
        <form action="{{ path('admin_prensa_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }} role="form">
		  <input type="hidden" name="_method" value="PUT" />  
          <div class="form-group">
			  {{ form_errors(edit_form.title) }}
              <label for="{{ edit_form.title.vars.id }}">Titulo</label>
			  {{ form_widget(edit_form.title, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
			  {{ form_errors(edit_form.preface) }}
              <label for="{{ edit_form.preface.vars.id }}">Copete</label>
			  {{ form_widget(edit_form.preface, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
			  {{ form_errors(edit_form.body) }}
              <label for="{{ edit_form.body.vars.id }}">Cuerpo</label>
			  {{ form_widget(edit_form.body, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          
		  <div class="form-group">
			  {{ form_errors(edit_form.position) }}
              <label for="{{ edit_form.position.vars.id }}">Posición</label>
			  {{ form_widget(edit_form.position, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">Guardar</button>
          </div>	
              {{ form_rest(edit_form) }}
          </form>
	  
	  {{ render(controller('MaithCommonAdminBundle:Albums:albumsData', {'id': entity.id, 'objectclass' : entity.fullClassName, 'listmode' : false }))}}
        </div>
      </section>
    </div>
    <div class="col-lg-8">
        <a href="{{ path('admin_prensa') }}" class="btn btn-info">
		  Volver al listado
	  </a>
		<form action="{{ path('admin_prensa_delete', { 'id': entity.id }) }}" method="post" onsubmit="return confirmDeleteDialog();" style="float: right;">
		  <input type="hidden" name="_method" value="DELETE" />
			{{ form_widget(delete_form) }}
		  <button class="btn btn-danger" type="submit">Eliminar</button>
		</form>
	</div>	
    
</div>
{% endblock %}

symfony/src/Maith/JuicioCiudadanoBundle/Resources/views/JuicioPrensa/index.html.twig
{% extends 'MaithJuicioCiudadanoBundle::adminlayout.html.twig' %}

{% block pagestylesheets %}
<link rel="stylesheet" href="{{ asset('bundles/maithjuiciociudadano/admin/vendor/chosen/chosen.min.css') }}">
<link rel="stylesheet" href="{{ asset('bundles/maithjuiciociudadano/admin/vendor/datatables/jquery.dataTables.css') }}">
{% endblock %}

{% block javascripts %}
<script src="{{ asset('bundles/maithjuiciociudadano/admin/vendor/chosen/chosen.jquery.min.js') }}"></script>
<script src="{{ asset('bundles/maithjuiciociudadano/admin/vendor/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('bundles/maithjuiciociudadano/admin/js/datatables.js') }}"></script>
{% endblock %}

{% block body -%}

<section class="panel">
  <header class="panel-heading">Listado de prensa</header>
  <div class="panel-body">
	<div class="table-responsive no-border">
	  <table class="table table-bordered table-striped mg-t datatable">
		<thead>
		  <tr>
			<th>Posición</th>
			<th>Titulo</th>
			<th>Copete</th>
			<th>Creado el</th>
			<th>Acciones</th>
		  </tr>
		</thead>
		<tfoot>
		  <tr>
            <th>Posición</th>
			<th>Titulo</th>
			<th>Copete</th>
			<th>Creado el</th>
			<th>Acciones</th>
		  </tr>
		</tfoot>
		<tbody>
		{% for entity in entities %}
			<tr>
			    <td>{{ entity.position }}</td>
			    <td>{{ entity.title }}</td>
			    <td>{{ entity.preface }}</td>
			    <td>{% if entity.created %}{{ entity.created|date('d/m/Y') }}{% endif %}</td>
			  <td>
				  <a href="{{ path('admin_prensa_edit', { 'id': entity.id }) }}"><i class="fa fa-pencil-square-o fa-2x"></i></a>
			  </td>
			</tr>
        {% endfor %}		  
		  </tbody>
		</table>
	  </div>
	</div>
  </section>
  

<div class="row">
  <div class="col-lg-12 text-center">
	  <a href="{{ path('admin_prensa_new') }}" class="btn btn-info">
		  Crear
	  </a>
  </div>
</div>
{% endblock %}

symfony/src/Maith/JuicioCiudadanoBundle/Resources/views/JuicioPrensa/new.html.twig
{% extends 'MaithJuicioCiudadanoBundle::adminlayout.html.twig' %}

{% block javascripts %}
<script src="{{ asset('bundles/maithjuiciociudadano/admin/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('bundles/maithjuiciociudadano/admin/js/basicstarttinymce.js') }}"></script>
{% endblock %}

{% block body -%}
<div class="row">
  <div class="col-lg-8">
    <section class="panel">
      <header class="panel-heading">Crear prensa</header>
      <div class="panel-body">
        <form action="{{ path('admin_prensa_create') }}" method="post" {{ form_enctype(form) }} role="form">
          <div class="form-group">
			  {{ form_errors(form.title) }}
              <label for="{{ form.title.vars.id }}">Titulo</label>
			  {{ form_widget(form.title, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
			  {{ form_errors(form.preface) }}
              <label for="{{ form.preface.vars.id }}">Copete</label>
			  {{ form_widget(form.preface, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
			  {{ form_errors(form.body) }}
              <label for="{{ form.body.vars.id }}">Cuerpo</label>
			  {{ form_widget(form.body, {'attr' : {'class' : 'form-control'}}) }}
          </div>
		  <div class="form-group">
			  {{ form_errors(form.position) }}
              <label for="{{ form.position.vars.id }}">Posición</label>
			  {{ form_widget(form.position, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">Guardar</button>
          </div>	
              {{ form_rest(form) }}
          </form>
        </div>
      </section>
    </div>
    <div class="col-lg-12 text-center">
	  <a href="{{ path('admin_prensa') }}" class="btn btn-info">
		  Volver al listado
	  </a>
	</div>
</div>
{% endblock %}

symfony/src/Maith/JuicioCiudadanoBundle/Resources/views/JuicioPrensa/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>JuicioPrensa</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>Preface</th>
                <td>{{ entity.preface }}</td>
            </tr>
            <tr>
                <th>Body</th>
                <td>{{ entity.body }}</td>
            </tr>
            <tr>
                <th>Position</th>
                <td>{{ entity.position }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ entity.created|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Updated</th>
                <td>{{ entity.updated|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ entity.slug }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_prensa') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_prensa_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}